sylius_grid:
    grids:
        setono_sylius_scheduler_admin_job_abstract:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_scheduler.model.job.class%"
                    repository:
                        method: createQueryBuilderByScheduleId
                        arguments:
                            scheduleId: $scheduleId
            fields:
                priority:
                    type: twig
                    label: sylius.ui.priority
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/position.html.twig"
                queue:
                    type: string
                    label: setono_sylius_scheduler.ui.queue
                    sortable: ~
                state:
                    type: twig
                    label: setono_sylius_scheduler.ui.state
                    sortable: ~
                    options:
                        template: "@SetonoSyliusSchedulerPlugin/Grid/Field/state.html.twig"
                createdAt:
                    type: datetime
                    label: setono_sylius_scheduler.ui.created_at
                    sortable: ~
                executeAfter:
                    type: datetime
                    label: setono_sylius_scheduler.ui.execute_after
                    sortable: ~
                closedAt:
                    type: datetime
                    label: setono_sylius_scheduler.ui.closed_at
                    sortable: ~

        setono_sylius_scheduler_admin_job:
            extends: setono_sylius_scheduler_admin_job_abstract
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_scheduler.model.job.class%"
                    repository:
                        method: createQueryBuilderByScheduleId
                        arguments:
                            scheduleId: $scheduleId
            sorting:
                priority: desc
            fields:
                command:
                    type: twig
                    label: setono_sylius_scheduler.ui.command
                    path: .
                    sortable: ~
                    options:
                        template: "@SetonoSyliusSchedulerPlugin/Grid/Field/commandAndArgs.html.twig"
                retryJobs:
                    type: twig
                    label: setono_sylius_scheduler.ui.retry_jobs
                    sortable: ~
                    options:
                        template: "@SetonoSyliusSchedulerPlugin/Grid/Field/itemsCount.html.twig"
            actions:
                item:
                    show:
                        type: show
                        options:
                            link:
                                parameters:
                                    id: resource.id
                                    scheduleId: resource.schedule.id
                    delete:
                        type: delete
                        options:
                            link:
                                parameters:
                                    id: resource.id
                                    scheduleId: resource.schedule.id
                subitem:
                    retries:
                        type: default
                        label: setono_sylius_scheduler.ui.action.retry_jobs_list
                        icon: list
                        options:
                            visible: resource.hasRetryJobs
                            link:
                                route: setono_sylius_scheduler_admin_job_retries_index
                                parameters:
                                    id: resource.id
                                    scheduleId: resource.schedule.id

        setono_sylius_scheduler_admin_job_retries:
            extends: setono_sylius_scheduler_admin_job_abstract
            driver:
                options:
                    repository:
                        method: createQueryBuilderByOriginalJobId
                        arguments:
                            originalJobId: $id
            fields:
                exitCode:
                    type: string
                    label: setono_sylius_scheduler.ui.exit_code
            actions:
                item:
                    show:
                        type: show
                        options:
                            link:
                                parameters:
                                    id: resource.id
                                    scheduleId: resource.schedule.id
