sylius_grid:
    grids:
        setono_sylius_scheduler_admin_schedule:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_scheduler.model.schedule.class%"
            sorting:
                priority: desc
            fields:
                code:
                    type: string
                    label: setono_sylius_scheduler.ui.code
                    sortable: ~
                name:
                    type: string
                    label: setono_sylius_scheduler.ui.name
                    sortable: ~
                queue:
                    type: string
                    label: setono_sylius_scheduler.ui.queue
                    sortable: ~
                command:
                    type: twig
                    label: setono_sylius_scheduler.ui.command
                    path: .
                    sortable: ~
                    options:
                        template: "@SetonoSyliusSchedulerPlugin/Grid/Field/commandAndArgs.html.twig"
                priority:
                    type: twig
                    label: sylius.ui.priority
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/position.html.twig"
                cronExpression:
                    type: string
                    label: setono_sylius_scheduler.ui.cron_expression
                    sortable: ~
                createdAt:
                    type: datetime
                    label: setono_sylius_scheduler.ui.created_at
                    sortable: ~
                jobs:
                    type: twig
                    label: setono_sylius_scheduler.ui.jobs
                    sortable: ~
                    options:
                        template: "@SetonoSyliusSchedulerPlugin/Grid/Field/itemsCount.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
