sylius_grid:
    templates:
        action:
            jobs_list: "@SetonoSyliusSchedulerPlugin/Grid/Action/jobs_list.html.twig"
    grids:
        setono_sylius_scheduler_admin_schedule:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_scheduler.model.schedule.class%"
                    repository:
                        method: createOrderedQueryBuilder
            sorting:
                priority: desc
            fields:
                priority:
                    type: twig
                    label: sylius.ui.priority
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/position.html.twig"
                queue:
                    type: string
                    label: setono_sylius_scheduler.ui.queue
                    sortable: ~
                code:
                    type: string
                    label: setono_sylius_scheduler.ui.code
                    sortable: ~
                name:
                    type: string
                    label: setono_sylius_scheduler.ui.name
                    sortable: ~
                command:
                    type: twig
                    label: setono_sylius_scheduler.ui.command
                    path: .
                    sortable: ~
                    options:
                        template: "@SetonoSyliusSchedulerPlugin/Grid/Field/commandAndArgs.html.twig"
                createdAt:
                    type: datetime
                    label: setono_sylius_scheduler.ui.created_at
                    sortable: ~
                nextRunAt:
                    type: twig
                    label: setono_sylius_scheduler.ui.next_run_at
                    path: .
                    sortable: ~
                    options:
                        template: "@SetonoSyliusSchedulerPlugin/Grid/Field/nextRunAt.html.twig"
                jobs:
                    type: twig
                    label: setono_sylius_scheduler.ui.jobs
                    sortable: ~
                    options:
                        template: "@SetonoSyliusSchedulerPlugin/Grid/Field/itemsCount.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                subitem:
                    jobs_list:
                        type: jobs_list
                        label: setono_sylius_scheduler.ui.action.jobs_list
                        options:
                            visible: resource.hasJobs
                            icon: tasks
                            link:
                                route: setono_sylius_scheduler_admin_job_index
                                parameters:
                                    scheduleId: resource.id
