# Routes (listed for better navigation):
# - setono_sylius_scheduler_admin_job_index
# - setono_sylius_scheduler_admin_job_create
# - setono_sylius_scheduler_admin_job_update
# - setono_sylius_scheduler_admin_job_bulk_delete
# - setono_sylius_scheduler_admin_job_delete

setono_sylius_scheduler_admin_job:
  resource: |
    alias: setono_sylius_scheduler.job
    section: admin
    templates: SyliusAdminBundle:Crud
    except: ['show']
    redirect: update
    grid: setono_sylius_scheduler_admin_job
    permission: true
    vars:
        all:
            subheader: setono_sylius_scheduler.ui.manage_jobs
            templates:
                form: "@SetonoSyliusSchedulerPlugin/Admin/Job/_form.html.twig"
        index:
            icon: tasks
        update:
            templates:
                form: "@SetonoSyliusSchedulerPlugin/Admin/Job/_form.html.twig"
  type: sylius.resource
