sylius_fixtures:
    suites:
        default:
            fixtures:
                setono_scheduler_schedule:
                    options:
                        custom:
                            schedule_oauth_clean:
                                code: 'schedule_oauth_clean'
                                name: 'Clean oauth every 2 minutes'
                                command: 'fos:oauth-server:clean'
                                cron_expression: '*/2 * * * *'
                            schedule_cache_clean:
                                code: 'schedule_cache_clean'
                                name: 'Clean cache every day'
                                command: 'cache:clean'
                                cron_expression: '0 0 * * *'
